services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notey-api
    ports:
      - "4005:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      CLIENT_URL: http://host.docker.internal:3000
      MONGODB_URI: mongodb://mongo:27017/notey
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: false
      MINIO_ACCESS_KEY: notey
      MINIO_SECRET_KEY: noteysecret
      MINIO_BUCKET: notey-files
    depends_on:
      - mongo
      - minio
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: notey-mongo
    ports:
      - "27019:27017"
    volumes:
      - notey_mongo_data:/data/db
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: notey-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: notey
      MINIO_ROOT_PASSWORD: noteysecret
    volumes:
      - notey_minio_data:/data
    restart: unless-stopped

volumes:
  notey_mongo_data:
  notey_minio_data:
